q = {
	self_id: 1570245877,
	user_id: 1476811518,
	time: 1773843246,
	message_id: 1441438710,
	message_seq: 1441438710,
	real_id: 1441438710,
	real_seq: '674',
	message_type: 'group',
	sender: { user_id: 1476811518, nickname: '我的电脑.', card: '', role: 'owner' },
	raw_message: 'wwwwwwww',
	font: 14,
	sub_type: 'normal',
	message: [{ type: 'text', data: { text: 'wwwwwwww' } }],
	message_format: 'array',
	post_type: 'message',
	group_id: 1085547365,
	group_name: 'ai测试',
	raw: {
		msgId: '7618598731791154044',
		msgRandom: '2108542983',
		msgSeq: '674',
		cntSeq: '0',
		chatType: 2,
		msgType: 2,
		subMsgType: 1,
		sendType: 0,
		senderUid: 'u_eE4doISGisH2t689lHJxsA',
		peerUid: '1085547365',
		channelId: '',
		guildId: '',
		guildCode: '0',
		fromUid: '0',
		fromAppid: '0',
		msgTime: '1773843246',
		msgMeta: {},
		sendStatus: 2,
		sendRemarkName: '',
		sendMemberName: '',
		sendNickName: '我的电脑.',
		guildName: '',
		channelName: '',
		elements: [{ elementType: 1, elementId: '7618598731791154043', elementGroupId: 0, extBufForUI: {}, textElement: { content: 'wwwwwwww', atType: 0, atUid: '0', atTinyId: '0', atNtUid: '', subElementType: 0, atChannelId: '0', linkInfo: null, atRoleId: '0', atRoleColor: 0, atRoleName: '', needNotify: 0 }, faceElement: null, marketFaceElement: null, replyElement: null, picElement: null, pttElement: null, videoElement: null, grayTipElement: null, arkElement: null, fileElement: null, liveGiftElement: null, markdownElement: null, structLongMsgElement: null, multiForwardMsgElement: null, giphyElement: null, walletElement: null, inlineKeyboardElement: null, textGiftElement: null, calendarElement: null, yoloGameResultElement: null, avRecordElement: null, structMsgElement: null, faceBubbleElement: null, shareLocationElement: null, tofuRecordElement: null, taskTopMsgElement: null, recommendedMsgElement: null, actionBarElement: null, prologueMsgElement: null, forwardMsgElement: null }],
		auxiliaryElements: [],
		records: [],
		emojiLikesList: [],
		commentCnt: '0',
		directMsgFlag: 0,
		directMsgMembers: [],
		peerName: 'ai测试',
		freqLimitInfo: null,
		editable: false,
		avatarMeta: '',
		avatarPendant: '',
		feedId: '',
		roleId: '0',
		timeStamp: '0',
		clientIdentityInfo: null,
		isImportMsg: false,
		atType: 0,
		roleType: 0,
		fromChannelRoleInfo: { roleId: '0', name: '', color: 0 },
		fromGuildRoleInfo: { roleId: '0', name: '', color: 0 },
		levelRoleInfo: { roleId: '0', name: '', color: 0 },
		recallTime: '0',
		isOnlineMsg: true,
		generalFlags: {},
		clientSeq: '0',
		fileGroupSize: null,
		foldingInfo: null,
		multiTransInfo: null,
		senderUin: '1476811518',
		peerUin: '1085547365',
		msgAttrs: {},
		anonymousExtInfo: null,
		nameType: 0,
		avatarFlag: 0,
		extInfoForUI: null,
		personalMedal: null,
		categoryManage: 0,
		msgEventInfo: null,
		sourceType: 1,
		id: 1441438710,
	},
};
w = {
	self_id: 1570245877,
	user_id: 1476811518,
	time: 1773843246,
	message_id: 1441438710,
	message_seq: 1441438710,
	real_id: 1441438710,
	real_seq: '674',
	message_type: 'group',
	sender: { user_id: 1476811518, nickname: '我的电脑.', card: '', role: 'owner' },
	raw_message: 'wwwwwwww',
	font: 14,
	sub_type: 'normal',
	message: [{ type: 'text', data: { text: 'wwwwwwww' } }],
	message_format: 'array',
	post_type: 'message',
	group_id: 1085547365,
	group_name: 'ai测试',
	raw: {
		msgId: '7618598731791154044',
		msgRandom: '2108542983',
		msgSeq: '674',
		cntSeq: '0',
		chatType: 2,
		msgType: 2,
		subMsgType: 1,
		sendType: 0,
		senderUid: 'u_eE4doISGisH2t689lHJxsA',
		peerUid: '1085547365',
		channelId: '',
		guildId: '',
		guildCode: '0',
		fromUid: '0',
		fromAppid: '0',
		msgTime: '1773843246',
		msgMeta: {},
		sendStatus: 2,
		sendRemarkName: '',
		sendMemberName: '',
		sendNickName: '我的电脑.',
		guildName: '',
		channelName: '',
		elements: [{ elementType: 1, elementId: '7618598731791154043', elementGroupId: 0, extBufForUI: {}, textElement: { content: 'wwwwwwww', atType: 0, atUid: '0', atTinyId: '0', atNtUid: '', subElementType: 0, atChannelId: '0', linkInfo: null, atRoleId: '0', atRoleColor: 0, atRoleName: '', needNotify: 0 }, faceElement: null, marketFaceElement: null, replyElement: null, picElement: null, pttElement: null, videoElement: null, grayTipElement: null, arkElement: null, fileElement: null, liveGiftElement: null, markdownElement: null, structLongMsgElement: null, multiForwardMsgElement: null, giphyElement: null, walletElement: null, inlineKeyboardElement: null, textGiftElement: null, calendarElement: null, yoloGameResultElement: null, avRecordElement: null, structMsgElement: null, faceBubbleElement: null, shareLocationElement: null, tofuRecordElement: null, taskTopMsgElement: null, recommendedMsgElement: null, actionBarElement: null, prologueMsgElement: null, forwardMsgElement: null }],
		auxiliaryElements: [],
		records: [],
		emojiLikesList: [],
		commentCnt: '0',
		directMsgFlag: 0,
		directMsgMembers: [],
		peerName: 'ai测试',
		freqLimitInfo: null,
		editable: false,
		avatarMeta: '',
		avatarPendant: '',
		feedId: '',
		roleId: '0',
		timeStamp: '0',
		clientIdentityInfo: null,
		isImportMsg: false,
		atType: 0,
		roleType: 0,
		fromChannelRoleInfo: { roleId: '0', name: '', color: 0 },
		fromGuildRoleInfo: { roleId: '0', name: '', color: 0 },
		levelRoleInfo: { roleId: '0', name: '', color: 0 },
		recallTime: '0',
		isOnlineMsg: true,
		generalFlags: {},
		clientSeq: '0',
		fileGroupSize: null,
		foldingInfo: null,
		multiTransInfo: null,
		senderUin: '1476811518',
		peerUin: '1085547365',
		msgAttrs: {},
		anonymousExtInfo: null,
		nameType: 0,
		avatarFlag: 0,
		extInfoForUI: null,
		personalMedal: null,
		categoryManage: 0,
		msgEventInfo: null,
		sourceType: 1,
		id: 1441438710,
	},
};
c = {
	self_id: 1570245877,
	user_id: 1476811518,
	time: 1773843507,
	message_id: 576989401,
	message_seq: 576989401,
	real_id: 576989401,
	real_seq: '675',
	message_type: 'group',
	sender: { user_id: 1476811518, nickname: '我的电脑.', card: '', role: 'owner' },
	raw_message: '[CQ:image,file=1D67FEF872A91AA614FA9D179F2BED15.jpg,sub_type=0,url=https://multimedia.nt.qq.com.cn/download?appid=1407&amp;fileid=EhSlySUcEb_JG18lLJS85qnYLb3ZkRjCLyD_CijNn8qA0qmTAzIEcHJvZFCAvaMBWhBhehcZ9JmLTrPcMsAttq9GegIHwYIBAm5q&amp;rkey=CAMSMPLgrGHNaLRF30NnZgoJu39GMYvgNwU_Bfa18jxiqmZypO8ircnTa0cN7bq3ZZLZIw,file_size=6082]',
	font: 14,
	sub_type: 'normal',
	message: [{ type: 'image', data: { summary: '', file: '1D67FEF872A91AA614FA9D179F2BED15.jpg', sub_type: 0, url: 'https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhSlySUcEb_JG18lLJS85qnYLb3ZkRjCLyD_CijNn8qA0qmTAzIEcHJvZFCAvaMBWhBhehcZ9JmLTrPcMsAttq9GegIHwYIBAm5q&rkey=CAMSMPLgrGHNaLRF30NnZgoJu39GMYvgNwU_Bfa18jxiqmZypO8ircnTa0cN7bq3ZZLZIw', file_size: '6082' } }],
	message_format: 'array',
	post_type: 'message',
	group_id: 1085547365,
	group_name: 'ai测试',
	raw: {
		msgId: '7618599856745541772',
		msgRandom: '1087447083',
		msgSeq: '675',
		cntSeq: '0',
		chatType: 2,
		msgType: 2,
		subMsgType: 2,
		sendType: 0,
		senderUid: 'u_eE4doISGisH2t689lHJxsA',
		peerUid: '1085547365',
		channelId: '',
		guildId: '',
		guildCode: '0',
		fromUid: '0',
		fromAppid: '0',
		msgTime: '1773843507',
		msgMeta: {},
		sendStatus: 2,
		sendRemarkName: '',
		sendMemberName: '',
		sendNickName: '我的电脑.',
		guildName: '',
		channelName: '',
		elements: [
			{
				elementType: 2,
				elementId: '7618599856745541771',
				elementGroupId: 0,
				extBufForUI: {},
				textElement: null,
				faceElement: null,
				marketFaceElement: null,
				replyElement: null,
				picElement: {
					picSubType: 0,
					picSubSubType: null,
					fileName: '1D67FEF872A91AA614FA9D179F2BED15.jpg',
					fileSize: '6082',
					picWidth: 474,
					picHeight: 474,
					original: false,
					md5HexStr: '1d67fef872a91aa614fa9d179f2bed15',
					sourcePath: 'C:\\Users\\李\\Documents\\Tencent Files\\1570245877\\nt_qq\\nt_data\\Pic\\2026-03\\Ori\\1d67fef872a91aa614fa9d179f2bed15.jpg',
					thumbPath: {},
					transferStatus: 0,
					progress: 0,
					picType: 1000,
					invalidState: 0,
					fileUuid: 'EhSlySUcEb_JG18lLJS85qnYLb3ZkRjCLyD_CijNn8qA0qmTAzIEcHJvZFCAvaMBWhBhehcZ9JmLTrPcMsAttq9GegIHwYIBAm5q',
					fileSubId: '',
					thumbFileSize: 0,
					fileBizId: null,
					downloadIndex: null,
					summary: '',
					emojiFrom: null,
					emojiWebUrl: null,
					emojiAd: { url: '', desc: '' },
					emojiMall: { packageId: 0, emojiId: 0 },
					emojiZplan: { actionId: 0, actionName: '', actionType: 0, playerNumber: 0, peerUid: '0', bytesReserveInfo: '' },
					originImageMd5: '',
					originImageUrl: '/download?appid=1407&fileid=EhSlySUcEb_JG18lLJS85qnYLb3ZkRjCLyD_CijNn8qA0qmTAzIEcHJvZFCAvaMBWhBhehcZ9JmLTrPcMsAttq9GegIHwYIBAm5q&spec=0',
					import_rich_media_context: null,
					isFlashPic: null,
					storeID: 1,
				},
				pttElement: null,
				videoElement: null,
				grayTipElement: null,
				arkElement: null,
				fileElement: null,
				liveGiftElement: null,
				markdownElement: null,
				structLongMsgElement: null,
				multiForwardMsgElement: null,
				giphyElement: null,
				walletElement: null,
				inlineKeyboardElement: null,
				textGiftElement: null,
				calendarElement: null,
				yoloGameResultElement: null,
				avRecordElement: null,
				structMsgElement: null,
				faceBubbleElement: null,
				shareLocationElement: null,
				tofuRecordElement: null,
				taskTopMsgElement: null,
				recommendedMsgElement: null,
				actionBarElement: null,
				prologueMsgElement: null,
				forwardMsgElement: null,
			},
		],
		auxiliaryElements: [],
		records: [],
		emojiLikesList: [],
		commentCnt: '0',
		directMsgFlag: 0,
		directMsgMembers: [],
		peerName: 'ai测试',
		freqLimitInfo: null,
		editable: false,
		avatarMeta: '',
		avatarPendant: '',
		feedId: '',
		roleId: '0',
		timeStamp: '0',
		clientIdentityInfo: null,
		isImportMsg: false,
		atType: 0,
		roleType: 0,
		fromChannelRoleInfo: { roleId: '0', name: '', color: 0 },
		fromGuildRoleInfo: { roleId: '0', name: '', color: 0 },
		levelRoleInfo: { roleId: '0', name: '', color: 0 },
		recallTime: '0',
		isOnlineMsg: true,
		generalFlags: {},
		clientSeq: '0',
		fileGroupSize: null,
		foldingInfo: null,
		multiTransInfo: null,
		senderUin: '1476811518',
		peerUin: '1085547365',
		msgAttrs: {},
		anonymousExtInfo: null,
		nameType: 0,
		avatarFlag: 0,
		extInfoForUI: null,
		personalMedal: null,
		categoryManage: 0,
		msgEventInfo: null,
		sourceType: 1,
		id: 576989401,
	},
};